#!/usr/bin/env ruby

# Initially copied from 
# https://github.com/tsaleh/dotfiles/blob/d5fcdac3135758a649ad26f951917cd9b659189c/vim/update_bundles

# Requirements:
#   jshint: node and jshint command line tool

# cool things not yet added:
#  git://github.com/kana/vim-textobj-user.git  define ones own text objects
# bundles looking interesting but currently (perhaps) not needed.
perhaps_latter = %w{
  git://github.com/Valloric/YouCompleteMe.git
  git://github.com/tsaleh/vim-tmux.git
  git://github.com/slim-template/vim-slim.git
  git://github.com/tpope/vim-rbenv.git
}


# git bundles for file handling
gb_files = %w{
  git://github.com/kien/ctrlp.vim.git
  git://github.com/scrooloose/nerdtree.git
}

# git bundles to support git
gb_git = %w{
  git://github.com/tpope/vim-fugitive.git
  git://github.com/tpope/vim-git.git
  git://github.com/gregsexton/gitv.git
  git://github.com/vim-scripts/Gist.vim.git
}

# General bundles to improve vim:
#   pasta makes pastes indent better.
gb_general = %w{
  git://github.com/godlygeek/csapprox.git
  git://github.com/sickill/vim-pasta.git
  git://github.com/tomtom/tcomment_vim.git
  git://github.com/tpope/vim-repeat.git
  git://github.com/tpope/vim-surround.git
  git://github.com/tpope/vim-unimpaired.git
  git://github.com/tpope/vim-vividchalk.git
  git://github.com/chrisbra/Recover.vim.git
  git://github.com/Lokaltog/vim-powerline.git
}

# language related bundles
gb_lang_web = %w{
  git://github.com/mattn/emmet-vim.git
  git://github.com/othree/html5.vim.git
  git://github.com/groenewege/vim-less.git
  git://github.com/hail2u/vim-css3-syntax.git
  git://github.com/pangloss/vim-javascript.git
  git://github.com/heavenshell/vim-jsdoc.git
  git://github.com/wookiehangover/jshint.vim.git
  git://github.com/elzr/vim-json.git
  git://github.com/vim-scripts/jQuery.git
}

gb_lang_etc = %w{
  git://github.com/tpope/vim-haml.git
  git://github.com/tpope/vim-markdown.git
}

git_bundles = gb_files + gb_git + gb_general + gb_lang_web + gb_lang_etc

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.rm_rf(bundles_dir)
FileUtils.mkdir(bundles_dir)
FileUtils.cd(bundles_dir)

git_bundles.each do |url|
  puts url
  `git clone -q #{url}`
end


# Dir["*/.git"].each {|f| FileUtils.rm_rf(f) }
